# Generated by Django 4.2.30 on 2026-09-05 21:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Şirket Adı')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
            ],
            options={
                'verbose_name': 'Şirket',
                'verbose_name_plural': 'Şirketler',
                'db_table': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(max_length=15, unique=True, verbose_name='Plaka')),
                ('driver_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Sürücü Adı')),
                ('driver_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Sürücü Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='fleet.company', verbose_name='Şirket')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
                'db_table': 'vehicles',
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=100, verbose_name='Soyad')),
                ('parent_name', models.CharField(blank=True, default='', max_length=200, verbose_name='Veli Adı')),
                ('parent_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Veli Telefon')),
                ('pickup_address', models.TextField(blank=True, default='', verbose_name='Alınma Adresi')),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Aylık Ücret')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='fleet.company', verbose_name='Şirket')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fleet.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Öğrenci',
                'verbose_name_plural': 'Öğrenciler',
                'db_table': 'students',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField(verbose_name='Ay')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Yıl')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tutar')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi'), ('overdue', 'Gecikmiş')], default='pending', max_length=10, verbose_name='Durum')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fleet.company', verbose_name='Şirket')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fleet.student', verbose_name='Öğrenci')),
            ],
            options={
                'verbose_name': 'Ödeme',
                'verbose_name_plural': 'Ödemeler',
                'db_table': 'payments',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('boarded', 'Bindi'), ('dropped', 'İndi'), ('absent', 'Gelmedi')], default='boarded', max_length=10, verbose_name='Durum')),
                ('direction', models.CharField(choices=[('morning', 'Sabah'), ('evening', 'Akşam')], default='morning', max_length=10, verbose_name='Yön')),
                ('logged_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Zamanı')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='fleet.student', verbose_name='Öğrenci')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='fleet.vehicle', verbose_name='Araç')),
            ],
            options={
                'verbose_name': 'Yoklama Kaydı',
                'verbose_name_plural': 'Yoklama Kayıtları',
                'db_table': 'attendance_logs',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('student', 'month', 'year'), name='unique_payment_per_student_month'),
        ),
    ]
