# Generated by Django 4.2.30 on 2026-09-06 11:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_at'], 'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.RemoveConstraint(
            model_name='payment',
            name='unique_payment_per_student_month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='month',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='year',
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Notlar'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Nakit'), ('transfer', 'Havale/EFT'), ('card', 'Kredi Kartı')], default='cash', max_length=20, verbose_name='Ödeme Yöntemi'),
        ),
        migrations.AddField(
            model_name='student',
            name='total_agreed_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Toplam Anlaşılan Ücret'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ödeme Tarihi'),
        ),
    ]
