# Generated by Django 4.2.30 on 2026-09-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_remove_company_user_company_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=15, verbose_name='Plaka'),
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('company', 'plate_number')},
        ),
    ]
