# Generated by Django 4.2.30 on 2026-09-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_alter_vehicle_plate_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['installment_number', 'paid_at'], 'verbose_name': 'Ödeme', 'verbose_name_plural': 'Ödemeler'},
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.IntegerField(default=1, verbose_name='Taksit No'),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Bekliyor'), ('paid', 'Ödendi')], default='pending', max_length=20, verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='student',
            name='installment_count',
            field=models.IntegerField(default=1, verbose_name='Taksit Sayısı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ödeme Tarihi'),
        ),
    ]
